# Application Port Setting
server:
  port: 80


# MySQL Connection Setting
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC
    username: root
    password: 1234

  jpa:
    properties:
      hibernate:
        # Printing executed queries to the console
        show_sql: true
        # Formatting queries print to the console with good readability
        format_sql: true

    hibernate:
      ddl-auto: create

    database-platform: org.hibernate.dialect.MySQL8Dialect

# Print a bind parameter that is print as a question mark in the query
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace;